// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderApp.Server.Data;

#nullable disable

namespace OrderApp.Server.Migrations
{
    [DbContext(typeof(OrderAppDbContext))]
    [Migration("20230321134640_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderApp.Server.Entity.OrderTable", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("OrderTable");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            Name = "New York Building 1",
                            State = "NY"
                        },
                        new
                        {
                            OrderId = 2,
                            Name = "California Hotel AJK",
                            State = "CA"
                        });
                });

            modelBuilder.Entity("OrderApp.Server.Entity.SubElementTable", b =>
                {
                    b.Property<int>("SubElementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubElementID"));

                    b.Property<int>("Element")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("SubElementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("WindowTableWindowID")
                        .HasColumnType("int");

                    b.HasKey("SubElementID");

                    b.HasIndex("WindowTableWindowID");

                    b.ToTable("SubElementTable");

                    b.HasData(
                        new
                        {
                            SubElementID = 1,
                            Element = 1,
                            Height = 1850,
                            SubElementType = "Doors",
                            Width = 1200,
                            WindowTableWindowID = 1
                        },
                        new
                        {
                            SubElementID = 2,
                            Element = 2,
                            Height = 1850,
                            SubElementType = "Window",
                            Width = 800,
                            WindowTableWindowID = 1
                        },
                        new
                        {
                            SubElementID = 3,
                            Element = 3,
                            Height = 1850,
                            SubElementType = "Window",
                            Width = 700,
                            WindowTableWindowID = 1
                        },
                        new
                        {
                            SubElementID = 4,
                            Element = 1,
                            Height = 2000,
                            SubElementType = "Window",
                            Width = 1500,
                            WindowTableWindowID = 2
                        },
                        new
                        {
                            SubElementID = 5,
                            Element = 1,
                            Height = 2200,
                            SubElementType = "Doors",
                            Width = 1400,
                            WindowTableWindowID = 3
                        },
                        new
                        {
                            SubElementID = 6,
                            Element = 2,
                            Height = 2200,
                            SubElementType = "Window",
                            Width = 600,
                            WindowTableWindowID = 3
                        },
                        new
                        {
                            SubElementID = 7,
                            Element = 1,
                            Height = 2000,
                            SubElementType = "Window",
                            Width = 1500,
                            WindowTableWindowID = 4
                        },
                        new
                        {
                            SubElementID = 8,
                            Element = 2,
                            Height = 2000,
                            SubElementType = "Window",
                            Width = 1500,
                            WindowTableWindowID = 4
                        });
                });

            modelBuilder.Entity("OrderApp.Server.Entity.WindowTable", b =>
                {
                    b.Property<int>("WindowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WindowID"));

                    b.Property<int>("OrderTableOrderId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOfWindows")
                        .HasColumnType("int");

                    b.Property<int>("TotalSubElements")
                        .HasColumnType("int");

                    b.Property<string>("WindowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WindowID");

                    b.HasIndex("OrderTableOrderId");

                    b.ToTable("WindowTable");

                    b.HasData(
                        new
                        {
                            WindowID = 1,
                            OrderTableOrderId = 1,
                            QuantityOfWindows = 4,
                            TotalSubElements = 3,
                            WindowName = "A51"
                        },
                        new
                        {
                            WindowID = 2,
                            OrderTableOrderId = 1,
                            QuantityOfWindows = 2,
                            TotalSubElements = 1,
                            WindowName = "C Zone 5"
                        },
                        new
                        {
                            WindowID = 3,
                            OrderTableOrderId = 2,
                            QuantityOfWindows = 3,
                            TotalSubElements = 2,
                            WindowName = "GLB"
                        },
                        new
                        {
                            WindowID = 4,
                            OrderTableOrderId = 2,
                            QuantityOfWindows = 10,
                            TotalSubElements = 2,
                            WindowName = "OHF"
                        });
                });

            modelBuilder.Entity("OrderApp.Server.Entity.SubElementTable", b =>
                {
                    b.HasOne("OrderApp.Server.Entity.WindowTable", "WindowTable")
                        .WithMany()
                        .HasForeignKey("WindowTableWindowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WindowTable");
                });

            modelBuilder.Entity("OrderApp.Server.Entity.WindowTable", b =>
                {
                    b.HasOne("OrderApp.Server.Entity.OrderTable", "OrderTable")
                        .WithMany()
                        .HasForeignKey("OrderTableOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderTable");
                });
#pragma warning restore 612, 618
        }
    }
}
